# Generated by Django 5.2.7 on 2026-02-06 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Countries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.CharField(default='USD', max_length=100),
        ),
        migrations.AddField(
            model_name='country',
            name='safety_index',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='country',
            name='capital',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
