# Generated by Django 5.2.7 on 2026-02-11 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='cost_index',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Cost of living index (higher = more expensive)', max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='safety_index',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Safety index out of 100', max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='travel_rating',
            field=models.DecimalField(decimal_places=1, default=1, help_text='Overall travel rating out of 10', max_digits=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
